### ISSUE TITLE
Multiple servers vs multiple proxies?

### ISSUE THREAD

**Issue by jonutella** [4Min4m/Reverse_Proxy#1]
This concept is very interesting, is it possible to configure multiple proxies on this server to lead the traffic through to the website? Because what if you need multiple load balancing servers?

**Comment by 4Min4m** [comment]
Yes, it is possible to configure multiple reverse proxies on a server to lead traffic to a website, and this is a common practice in many environments. The setup you are describing is often referred to as a "reverse proxy load balancing" configuration.

In this setup, the reverse proxies act as an intermediate layer between the clients (users) and the backend web servers hosting the website. When a user makes a request to access the website, it is received by one of the reverse proxies, which then forwards the request to one of the backend web servers based on the configured load balancing algorithm. The backend web server processes the request and sends the response back through the reverse proxy to the user.

The advantages of using multiple reverse proxies in this context are:

Load balancing: By distributing the incoming traffic across multiple backend servers, you can achieve better performance, improved response times, and higher availability for the website.

High availability: If one of the reverse proxies or backend servers fails, the other reverse proxies and servers can continue to handle the incoming traffic, providing fault tolerance and high availability for the website.

Scalability: As the website's traffic grows, you can add more backend servers and reverse proxies to handle the increased load, allowing you to scale your infrastructure easily.

Common load balancing algorithms used in reverse proxy setups include round-robin (requests are distributed in a circular manner among backend servers), least connections (requests are sent to the server with the fewest active connections), and IP hash (requests from the same IP address are sent to the same backend server to maintain session persistence).

There are several reverse proxy software options available, such as Nginx, HAProxy, and Apache HTTP Server, that can be used to implement this kind of setup. The exact configuration will depend on the specific software being used and the requirements of your environment.

Overall, using multiple reverse proxies in conjunction with load balancing servers is a powerful way to enhance the performance, scalability, and availability of a website or web application.
